# Generated by Django 5.0.3 on 2024-06-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='sinopse',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
