# Generated by Django 5.0.3 on 2024-06-22 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_movieratingus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieRatingUS',
        ),
    ]
