# Generated by Django 5.0.3 on 2024-06-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_userrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='user_rating',
            field=models.FloatField(default=0),
        ),
    ]
