# Generated by Django 5.0.3 on 2024-06-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_movie_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrating',
            name='nota',
            field=models.IntegerField(default=0),
        ),
    ]
