# Generated by Django 5.0.3 on 2024-06-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_userrating_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrating',
            name='nota',
            field=models.IntegerField(),
        ),
    ]
