# Generated by Django 5.0.3 on 2024-06-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_movie_num_ratings_remove_movie_user_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='showtime1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='showtime2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='showtime3',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='showtime4',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='MovieShowtimes',
        ),
    ]
